### PR TITLE
Dark theme fixes

### LINKED ISSUE #42: Dark theme fix for add delegate and remove delegate modal

### PR DESCRIPTION
**Pull request by gaurav8628**
#42

### CODE REVIEW

File: packages/react-app/src/components/AddDelegateModal.js [hunk 1]
```diff
@@ -49,13 +50,14 @@ export default function AddDelegateModal({
...
 
     return (
-        <Overlay>
+        <ThemeProvider theme={themes}>
+            <Overlay>
             <AliasModal ref={modalRef} background={themes}>
                 <Item align="flex-start">
                     <H2 textTransform="uppercase" spacing="0.1em">
-                    <Span weight="200">Add </Span><Span bg="#674c9f" color="#fff" weight="600" padding="0px 8px">Delegate</Span>
+                    <Span weight="200"  weight="200" color={themes.scheme=="dark" ? "white" : "black"}>Add </Span><Span bg="#674c9f" color="#fff" weight="600" padding="0px 8px">Delegate</Span>
```
Comment (nilesh46) [inline packages/react-app/src/components/AddDelegateModal.js:58]: Use appropriate color from theme object only. For reference, see AliasVerificationModal

**Review by nilesh46 — CHANGES_REQUESTED** [review]

**Review by nilesh46 — APPROVED** [review]
